### ISSUE TITLE
Update GitHub templates

### ISSUE THREAD

**Issue by tomscholz** [Dogfalo/materialize#4848]
Constructive feedback is welcome. 
We need a new pull request tempate and I think a rework of the issue template would be great as well. If your native language is English or you have extraordinary English skills, then please correct my typos. Also see https://github.com/Dogfalo/materialize/pull/4843

What the templates should make clear:
* Keeping the issue and pull request counter as low as possible
* No duplicate issues / pull requests (See above)
* An issue should be opened before creating a PR, if the change is obvious, something like a typo fix, a issue should not be necessary
* No "how to" questions. Use Stackoverflow or gitter for these instead

**Comment by tomscholz** [comment]
## Issue template draft:
```
Before opening an issue here make sure, that you have read the template completly through

When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](stackoverflow.com/questions/tagged/materialize) or in our [Gitter](https://gitter.im/Dogfalo/materialize) channel

- Read the [contributing guidelines](https://github.com/Dogfalo/materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure to go through our [labels](https://github.com/Dogfalo/materialize/labels)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs

<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->
<!--- and post a link to the corresponding [material design specification](https://material.io/guidelines/components/). -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if applicable): 

```

**Comment by DanielRuf** [comment]
Will take a closer look later.

**Comment by smileytechguy** [comment]
I like it.  A suggestion I'd like to make is to add a troubleshooting checklist, such as latest version, tired isolated (no additional plugins), checked console, stuff like that.  We could use the homebrew-cask repository's as an example `https://github.com/caskroom/homebrew-cask/issues/new`

**Comment by DanielRuf** [comment]
@smileytechguy that's what I also had in my mind. This might help to reduce issues which only occur in unsupported browsers and Materialize versions and to know what they've already tried. (Checkboxes like "disabled / flushed the cache").

We should provide master releases (bleeding edge) so they can test it against the current master branch as there are often issues fixed but without any relation to a PR or issue.

**Comment by tomscholz** [comment]
@smileytechguy 
Here are some templates that I have found. Did you meant something like that?
* [Urigo/angular-meteor](https://github.com/Urigo/angular-meteor/blob/master/.github/ISSUE_TEMPLATE.md)
* [Affected browsers](https://github.com/Polymer/polymer/blob/master/.github/ISSUE_TEMPLATE.md#browsers-affected)
* [Im-not-a-dummy-so-ive-checked-these](https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/issue_template.md#im-not-a-dummy-so-ive-checked-these)

---
>This might help to reduce issues which only occur in unsupported browsers and Materialize versions and to know what they've already tried. (Checkboxes like "disabled / flushed the cache").

@DanielRuf Right. See:
> - Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs

---
I just had a thought that we should move general information in the CONTRIBUTING.md to keep the templates nice and clean. What do you think?

> Keeping the issue and pull request counter as low as possible
No duplicate issues / pull requests (See above)
An issue should be opened before creating a PR, if the change is obvious, something like a typo fix, a issue should not be necessary

---
I think just a quick note on how to compile the files yourself or going through the commits should be enough.

> We should provide master releases (bleeding edge) so they can test it against the current master branch as there are often issues fixed but without any relation to a PR or issue.

**Comment by DanielRuf** [comment]
So far very good and important points there.

We should keep an eye on the code of conduct and styleguides of other great projects and adapt their actively used templates (I guess you already know about the new community page under insights @tomscholz).

**Comment by tomscholz** [comment]
I don't have access to the projects settings. But yeah, I know about that page

**Comment by tomscholz** [comment]
## Pull request template draft:
```
<!--- Provide a general summary of your changes in the Title above -->

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Screenshots (if appropriate) or codepen:
Add supplemental screenshots or code examples. Look for a codepen template in our **CONTRIBUTING** document.

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
```

**Comment by Dogfalo** [comment]
First line probably unnecessary.
Also link the contributing document whenever referenced, otherwise, lgtm

**Comment by tomscholz** [comment]
@Dogfalo Pull request template added in https://github.com/Dogfalo/materialize/commit/5636ead859a589478c8e5b1b65c24ee531dfbd44

**Comment by Dogfalo** [comment]
Issue template looks good, please add that in

**Comment by tomscholz** [comment]
Added in https://github.com/Dogfalo/materialize/commit/1b21d70fe52045d638fd23e5a09afbd5e0765af1
